[project]
name = "api"
version = "0.1.0"
dependencies = [
  "fastapi>=0.115",
  "uvicorn[standard]",
  "httpx>=0.27",
  "asyncpg>=0.29",
  "pandas>=2.2",
  "pandas-ta>=0.3.14b0",
  "python-dotenv>=1.0",
  "structlog>=24.1",
]

[tool.uv]
package = true
